image_urls = {
	"ENGLISH POINTER" : "https://www.fci.be/Nomenclature/Illustrations/001g07.jpg",
	"ENGLISH SETTER" : "https://www.fci.be/Nomenclature/Illustrations/002g07.jpg",
	"CAIRN TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/004g03.jpg",
	"ENGLISH COCKER SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/005g08.jpg",
	"GORDON SETTER" : "https://www.fci.be/Nomenclature/Illustrations/006g07.jpg",
	"AIREDALE TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/007g03.jpg",
	"AUSTRALIAN TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/008g03.jpg",
	"BEDLINGTON TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/009g03.jpg",
	"BORDER TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/010g03.jpg",
	"BULL TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/011g03.jpg",
	"FOX TERRIER (SMOOTH)" : "https://www.fci.be/Nomenclature/Illustrations/012g03.jpg",
	"ENGLISH TOY TERRIER (BLACK &TAN)" : "https://www.fci.be/Nomenclature/Illustrations/013g03.jpg",
	"SWEDISH VALLHUND" : "https://www.fci.be/Nomenclature/Illustrations/014g05.jpg",
	"OLD ENGLISH SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/016g01.jpg",
	"GRIFFON NIVERNAIS" : "https://www.fci.be/Nomenclature/Illustrations/017g06.jpg",
	"BRIQUET GRIFFON VENDEEN" : "https://www.fci.be/Nomenclature/Illustrations/019g06.jpg",
	"ARIEGEOIS" : "https://www.fci.be/Nomenclature/Illustrations/020g06.jpg",
	"GASCON SAINTONGEOIS" : "https://www.fci.be/Nomenclature/Illustrations/021g06-1.jpg",
	"GREAT GASCONY BLUE" : "https://www.fci.be/Nomenclature/Illustrations/022g06.jpg",
	"POITEVIN" : "https://www.fci.be/Nomenclature/Illustrations/024g06.jpg",
	"BILLY" : "https://www.fci.be/Nomenclature/Illustrations/025g06.jpg",
	"ARTOIS HOUND" : "https://www.fci.be/Nomenclature/Illustrations/028g06.jpg",
	"PORCELAINE" : "https://www.fci.be/Nomenclature/Illustrations/030g06.jpg",
	"SMALL BLUE GASCONY" : "https://www.fci.be/Nomenclature/Illustrations/031g06.jpg",
	"BLUE GASCONY GRIFFON" : "https://www.fci.be/Nomenclature/Illustrations/032g06.jpg",
	"NORMAN ARTESIEN BASSET" : "https://www.fci.be/Nomenclature/Illustrations/034g06.jpg",
	"BLUE GASCONY BASSET" : "https://www.fci.be/Nomenclature/Illustrations/035g06.jpg",
	"PORTUGUESE WATER DOG" : "https://www.fci.be/Nomenclature/Illustrations/037g08.jpg",
	"WELSH CORGI (CARDIGAN)" : "https://www.fci.be/Nomenclature/Illustrations/038g01.jpg",
	"WELSH CORGI (PEMBROKE)" : "https://www.fci.be/Nomenclature/Illustrations/039g01.jpg",
	"JÄMTHUND" : "https://www.fci.be/Nomenclature/Illustrations/042g05.jpg",
	"BEAUCE SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/044g01.jpg",
	"BERNESE MOUNTAIN DOG" : "https://www.fci.be/Nomenclature/Illustrations/045g02.jpg",
	"APPENZELL CATTLE DOG" : "https://www.fci.be/Nomenclature/Illustrations/046g02.jpg",
	"ENTLEBUCH CATTLE DOG" : "https://www.fci.be/Nomenclature/Illustrations/047g02.jpg",
	"KARELIAN BEAR DOG" : "https://www.fci.be/Nomenclature/Illustrations/048g05-1.jpg",
	"FINNISH SPITZ" : "https://www.fci.be/Nomenclature/Illustrations/049g05-1.jpg",
	"POLISH HOUND" : "https://www.fci.be/Nomenclature/Illustrations/052g06.jpg",
	"KOMONDOR" : "https://www.fci.be/Nomenclature/Illustrations/053g01.jpg",
	"KUVASZ" : "https://www.fci.be/Nomenclature/Illustrations/054g01.jpg",
	"PULI" : "https://www.fci.be/Nomenclature/Illustrations/055g01.jpg",
	"PUMI" : "https://www.fci.be/Nomenclature/Illustrations/056g01.jpg",
	"HUNGARIAN SHORT-HAIRED POINTER (VIZSLA)" : "https://www.fci.be/Nomenclature/Illustrations/057g07.jpg",
	"GREAT SWISS MOUNTAIN DOG" : "https://www.fci.be/Nomenclature/Illustrations/058g02.jpg",
	"SWISS HOUND" : "https://www.fci.be/Nomenclature/Illustrations/059g06-1.jpg",
	"SMALL SWISS HOUND" : "https://www.fci.be/Nomenclature/Illustrations/060g06-1.jpg",
	"ST. BERNARD" : "https://www.fci.be/Nomenclature/Illustrations/061g02-1.jpg",
	"COARSE-HAIRED STYRIAN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/062g06.jpg",
	"AUSTRIAN BLACK AND TAN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/063g06.jpg",
	"FAWN BRITTANY GRIFFON" : "https://www.fci.be/Nomenclature/Illustrations/066g06.jpg",
	"LAKELAND TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/070g03.jpg",
	"MANCHESTER TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/071g03.jpg",
	"NORWICH TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/072g03.jpg",
	"SCOTTISH TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/073g03.jpg",
	"SEALYHAM TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/074g03.jpg",
	"SKYE TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/075g03.jpg",
	"STAFFORDSHIRE BULL TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/076g03.jpg",
	"WELSH TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/078g03.jpg",
	"GRIFFON BELGE" : "https://www.fci.be/Nomenclature/Illustrations/081g09.jpg",
	"PETIT BRABANÇON" : "https://www.fci.be/Nomenclature/Illustrations/082g09.jpg",
	"WEST HIGHLAND WHITE TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/085g03.jpg",
	"YORKSHIRE TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/086g03.jpg",
	"SHETLAND SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/088g01.jpg",
	"PORTUGUESE SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/093g01.jpg",
	"PORTUGUESE WARREN HOUND-PORTUGUESE PODENGO" : "https://www.fci.be/Nomenclature/Illustrations/094g05-1.jpg",
	"BRITTANY SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/095g07.jpg",
	"RAFEIRO OF ALENTEJO" : "https://www.fci.be/Nomenclature/Illustrations/096g02.jpg",
	"GERMAN SPITZ" : "https://www.fci.be/Nomenclature/Illustrations/097g05-1.jpg",
	"GERMAN WIRE- HAIRED POINTING DOG" : "https://www.fci.be/Nomenclature/Illustrations/098g07.jpg",
	"WEIMARANER" : "https://www.fci.be/Nomenclature/Illustrations/099g07-1.jpg",
	"FRENCH BULLDOG" : "https://www.fci.be/Nomenclature/Illustrations/101g09.jpg",
	"GERMAN HUNTING TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/103g03-1.jpg",
	"GERMAN SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/104g08.jpg",
	"FRENCH WATER DOG" : "https://www.fci.be/Nomenclature/Illustrations/105g08.jpg",
	"BLUE PICARDY SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/106g07.jpg",
	"WIRE-HAIRED POINTING GRIFFON KORTHALS" : "https://www.fci.be/Nomenclature/Illustrations/107g07.jpg",
	"PICARDY SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/108g07.jpg",
	"CLUMBER SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/109g08.jpg",
	"CURLY COATED RETRIEVER" : "https://www.fci.be/Nomenclature/Illustrations/110g08.jpg",
	"GOLDEN RETRIEVER" : "https://www.fci.be/Nomenclature/Illustrations/111g08.jpg",
	"BRIARD" : "https://www.fci.be/Nomenclature/Illustrations/113g01.jpg",
	"PONT-AUDEMER SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/114g07.jpg",
	"SAINT GERMAIN POINTER" : "https://www.fci.be/Nomenclature/Illustrations/115g07.jpg",
	"DOGUE DE BORDEAUX" : "https://www.fci.be/Nomenclature/Illustrations/116g02.jpg",
	"DEUTSCH LANGHAAR" : "https://www.fci.be/Nomenclature/Illustrations/117g07.jpg",
	"LARGE MUNSTERLANDER" : "https://www.fci.be/Nomenclature/Illustrations/118g07.jpg",
	"GERMAN SHORT- HAIRED POINTING DOG" : "https://www.fci.be/Nomenclature/Illustrations/119g07.jpg",
	"FLAT COATED RETRIEVER" : "https://www.fci.be/Nomenclature/Illustrations/121g08.jpg",
	"LABRADOR RETRIEVER" : "https://www.fci.be/Nomenclature/Illustrations/122g08.jpg",
	"FIELD SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/123g08.jpg",
	"ENGLISH SPRINGER SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/125g08.jpg",
	"WELSH SPRINGER SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/126g08.jpg",
	"SUSSEX SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/127g08.jpg",
	"KING CHARLES SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/128g09.jpg",
	"SMÅLANDSSTÖVARE" : "https://www.fci.be/Nomenclature/Illustrations/129g06.jpg",
	"DREVER" : "https://www.fci.be/Nomenclature/Illustrations/130g06.jpg",
	"SCHILLERSTÖVARE" : "https://www.fci.be/Nomenclature/Illustrations/131g06.jpg",
	"HAMILTONSTÖVARE" : "https://www.fci.be/Nomenclature/Illustrations/132g06.jpg",
	"FRENCH POINTING DOG - GASCOGNE TYPE" : "https://www.fci.be/Nomenclature/Illustrations/133g07.jpg",
	"FRENCH POINTING DOG - PYRENEAN TYPE" : "https://www.fci.be/Nomenclature/Illustrations/134g07.jpg",
	"SWEDISH LAPPHUND" : "https://www.fci.be/Nomenclature/Illustrations/135g05.jpg",
	"CAVALIER KING CHARLES SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/136g09.jpg",
	"PYRENEAN MOUNTAIN DOG" : "https://www.fci.be/Nomenclature/Illustrations/137g02.jpg",
	"PYRENEAN SHEEPDOG - SMOOTH FACED" : "https://www.fci.be/Nomenclature/Illustrations/138g01.jpg",
	"LONG-HAIRED PYRENEAN SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/141g01.jpg",
	"DOBERMANN" : "https://www.fci.be/Nomenclature/Illustrations/143g02.jpg",
	"BOXER" : "https://www.fci.be/Nomenclature/Illustrations/144g02.jpg",
	"DACHSHUND" : "https://www.fci.be/Nomenclature/Illustrations/148g04-1.jpg",
	"BULLDOG" : "https://www.fci.be/Nomenclature/Illustrations/149g02.jpg",
	"SERBIAN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/150g06.jpg",
	"ISTRIAN SHORT-HAIRED HOUND" : "https://www.fci.be/Nomenclature/Illustrations/151g06.jpg",
	"ISTRIAN WIRE-HAIRED HOUND" : "https://www.fci.be/Nomenclature/Illustrations/152g06.jpg",
	"DALMATIAN" : "https://www.fci.be/Nomenclature/Illustrations/153g06.jpg",
	"POSAVATZ HOUND" : "https://www.fci.be/Nomenclature/Illustrations/154g06.jpg",
	"BOSNIAN BROKEN-HAIRED HOUND - CALLED BARAK" : "https://www.fci.be/Nomenclature/Illustrations/155g06.jpg",
	"COLLIE ROUGH" : "https://www.fci.be/Nomenclature/Illustrations/156g01.jpg",
	"GREYHOUND" : "https://www.fci.be/Nomenclature/Illustrations/158g10.jpg",
	"ENGLISH FOXHOUND" : "https://www.fci.be/Nomenclature/Illustrations/159g06.jpg",
	"BEAGLE" : "https://www.fci.be/Nomenclature/Illustrations/161g06.jpg",
	"WHIPPET" : "https://www.fci.be/Nomenclature/Illustrations/162g10.jpg",
	"BASSET HOUND" : "https://www.fci.be/Nomenclature/Illustrations/163g06.jpg",
	"DEERHOUND" : "https://www.fci.be/Nomenclature/Illustrations/164g10.jpg",
	"GERMAN SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/166g01-1.jpg",
	"DANDIE DINMONT TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/168g03.jpg",
	"FOX TERRIER (WIRE)" : "https://www.fci.be/Nomenclature/Illustrations/169g03.jpg",
	"CASTRO LABOREIRO DOG" : "https://www.fci.be/Nomenclature/Illustrations/170g02.jpg",
	"POODLE" : "https://www.fci.be/Nomenclature/Illustrations/172g09.jpg",
	"ESTRELA MOUNTAIN DOG" : "https://www.fci.be/Nomenclature/Illustrations/173g02.jpg",
	"FRENCH SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/175g07.jpg",
	"PICARDY SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/176g01.jpg",
	"ARIEGE POINTING DOG" : "https://www.fci.be/Nomenclature/Illustrations/177g07-1.jpg",
	"BOURBONNAIS POINTING DOG" : "https://www.fci.be/Nomenclature/Illustrations/179g07.jpg",
	"AUVERGNE POINTER" : "https://www.fci.be/Nomenclature/Illustrations/180g07.jpg",
	"GIANT SCHNAUZER" : "https://www.fci.be/Nomenclature/Illustrations/181g02.jpg",
	"SCHNAUZER" : "https://www.fci.be/Nomenclature/Illustrations/182g02.jpg",
	"MINIATURE SCHNAUZER" : "https://www.fci.be/Nomenclature/Illustrations/183g02.jpg",
	"GERMAN PINSCHER" : "https://www.fci.be/Nomenclature/Illustrations/184g02.jpg",
	"MINIATURE PINSCHER" : "https://www.fci.be/Nomenclature/Illustrations/185g02.jpg",
	"AFFENPINSCHER" : "https://www.fci.be/Nomenclature/Illustrations/186g02.jpg",
	"PORTUGUESE POINTING DOG" : "https://www.fci.be/Nomenclature/Illustrations/187g07.jpg",
	"FINNISH LAPPONIAN DOG" : "https://www.fci.be/Nomenclature/Illustrations/189g05-1.jpg",
	"KROMFOHRLÄNDER" : "https://www.fci.be/Nomenclature/Illustrations/192g09.jpg",
	"BORZOI - RUSSIAN HUNTING SIGHTHOUND" : "https://www.fci.be/Nomenclature/Illustrations/193g10.jpg",
	"BERGAMASCO SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/194g01-1.jpg",
	"CIRNECO DELL'ETNA" : "https://www.fci.be/Nomenclature/Illustrations/199g05-1.jpg",
	"ITALIAN POINTING DOG" : "https://www.fci.be/Nomenclature/Illustrations/202g07.jpg",
	"NORWEGIAN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/203g06.jpg",
	"CHOW CHOW" : "https://www.fci.be/Nomenclature/Illustrations/205g05.jpg",
	"JAPANESE CHIN" : "https://www.fci.be/Nomenclature/Illustrations/206g09.jpg",
	"PEKINGESE" : "https://www.fci.be/Nomenclature/Illustrations/207g09.jpg",
	"SHIH TZU" : "https://www.fci.be/Nomenclature/Illustrations/208g09.jpg",
	"TIBETAN TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/209g09.jpg",
	"CANADIAN ESKIMO DOG" : "https://www.fci.be/Nomenclature/Illustrations/211g05.jpg",
	"SAMOYED" : "https://www.fci.be/Nomenclature/Illustrations/212g05.jpg",
	"HANOVERIAN SCENT HOUND" : "https://www.fci.be/Nomenclature/Illustrations/213g06-1.jpg",
	"BICHON FRISE" : "https://www.fci.be/Nomenclature/Illustrations/215g09-1.jpg",
	"BAVARIAN MOUNTAIN SCENT HOUND" : "https://www.fci.be/Nomenclature/Illustrations/217g06-1.jpg",
	"CHIHUAHUA" : "https://www.fci.be/Nomenclature/Illustrations/218g09-1.jpg",
	"FRENCH TRICOLOUR HOUND" : "https://www.fci.be/Nomenclature/Illustrations/219g06.jpg",
	"FRENCH WHITE & BLACK HOUND" : "https://www.fci.be/Nomenclature/Illustrations/220g06.jpg",
	"WETTERHOUN" : "https://www.fci.be/Nomenclature/Illustrations/221g08-1.jpg",
	"STABIJHOUN" : "https://www.fci.be/Nomenclature/Illustrations/222g07-1.jpg",
	"DUTCH SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/223g01-1.jpg",
	"DRENTSCHE PARTRIDGE DOG" : "https://www.fci.be/Nomenclature/Illustrations/224g07-1.jpg",
	"FILA BRASILEIRO" : "https://www.fci.be/Nomenclature/Illustrations/225g02.jpg",
	"LHASA APSO" : "https://www.fci.be/Nomenclature/Illustrations/227g09.jpg",
	"AFGHAN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/228g10.jpg",
	"SERBIAN TRICOLOUR HOUND" : "https://www.fci.be/Nomenclature/Illustrations/229g06.jpg",
	"TIBETAN SPANIEL" : "https://www.fci.be/Nomenclature/Illustrations/231g09.jpg",
	"DEUTSCH STICHELHAAR" : "https://www.fci.be/Nomenclature/Illustrations/232g07.jpg",
	"LITTLE LION DOG" : "https://www.fci.be/Nomenclature/Illustrations/233g09.jpg",
	"XOLOITZCUINTLE" : "https://www.fci.be/Nomenclature/Illustrations/234g05-1.jpg",
	"GREAT DANE" : "https://www.fci.be/Nomenclature/Illustrations/235g02.jpg",
	"AUSTRALIAN SILKY TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/236g03.jpg",
	"NORWEGIAN BUHUND" : "https://www.fci.be/Nomenclature/Illustrations/237g05.jpg",
	"MUDI" : "https://www.fci.be/Nomenclature/Illustrations/238g01.jpg",
	"HUNGARIAN WIRE-HAIRED POINTER" : "https://www.fci.be/Nomenclature/Illustrations/239g07.jpg",
	"HUNGARIAN GREYHOUND" : "https://www.fci.be/Nomenclature/Illustrations/240g10.jpg",
	"HUNGARIAN HOUND - TRANSYLVANIAN SCENT HOUND" : "https://www.fci.be/Nomenclature/Illustrations/241g06.jpg",
	"NORWEGIAN ELKHOUND GREY" : "https://www.fci.be/Nomenclature/Illustrations/242g05.jpg",
	"ALASKAN MALAMUTE" : "https://www.fci.be/Nomenclature/Illustrations/243g05.JPG",
	"CESKY TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/246g03.jpg",
	"POLISH LOWLAND SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/251g01.jpg",
	"TATRA SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/252g01.jpg",
	"PUG" : "https://www.fci.be/Nomenclature/Illustrations/253g09.jpg",
	"AKITA" : "https://www.fci.be/Nomenclature/Illustrations/255g05.jpg",
	"SHIBA" : "https://www.fci.be/Nomenclature/Illustrations/257g05.jpg",
	"JAPANESE TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/259g03.jpg",
	"TOSA" : "https://www.fci.be/Nomenclature/Illustrations/260g02.jpg",
	"HOKKAIDO" : "https://www.fci.be/Nomenclature/Illustrations/261g05.jpg",
	"JAPANESE SPITZ" : "https://www.fci.be/Nomenclature/Illustrations/262g05.jpg",
	"NORWEGIAN LUNDEHUND" : "https://www.fci.be/Nomenclature/Illustrations/265g05.jpg",
	"HYGEN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/266g06.jpg",
	"HALDEN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/267g06.jpg",
	"NORWEGIAN ELKHOUND BLACK" : "https://www.fci.be/Nomenclature/Illustrations/268g05.jpg",
	"SIBERIAN HUSKY" : "https://www.fci.be/Nomenclature/Illustrations/270g05.jpg",
	"BEARDED COLLIE" : "https://www.fci.be/Nomenclature/Illustrations/271g01.jpg",
	"NORFOLK TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/272g03.jpg",
	"GREENLAND DOG" : "https://www.fci.be/Nomenclature/Illustrations/274g05.jpg",
	"BRAZILIAN TRACKER" : "https://www.fci.be/Nomenclature/Illustrations/275g06.jpg",
	"NORRBOTTENSPITZ" : "https://www.fci.be/Nomenclature/Illustrations/276g05.jpg",
	"CROATIAN SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/277g01.jpg",
	"KARST SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/278g02.jpg",
	"MONTENEGRIN MOUNTAIN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/279g06.jpg",
	"GRAND GRIFFON VENDEEN" : "https://www.fci.be/Nomenclature/Illustrations/282g06.jpg",
	"AUSTRALIAN CATTLE DOG" : "https://www.fci.be/Nomenclature/Illustrations/287g01.jpg",
	"CHINESE CRESTED DOG" : "https://www.fci.be/Nomenclature/Illustrations/288g09.jpg",
	"ICELANDIC SHEEPDOG" : "https://www.fci.be/Nomenclature/Illustrations/289g05.jpg",
	"BEAGLE HARRIER" : "https://www.fci.be/Nomenclature/Illustrations/290g06.jpg",
	"EURASIAN" : "https://www.fci.be/Nomenclature/Illustrations/291g05-1.jpg",
	"DOGO ARGENTINO" : "https://www.fci.be/Nomenclature/Illustrations/292g02.jpg",
	"AUSTRALIAN KELPIE" : "https://www.fci.be/Nomenclature/Illustrations/293g01.jpg",
	"OTTERHOUND" : "https://www.fci.be/Nomenclature/Illustrations/294g06.jpg",
	"COLLIE SMOOTH" : "https://www.fci.be/Nomenclature/Illustrations/296g01.jpg",
	"BORDER COLLIE" : "https://www.fci.be/Nomenclature/Illustrations/297g01.jpg",
	"ROMAGNA WATER DOG" : "https://www.fci.be/Nomenclature/Illustrations/298g08-1.jpg",
	"BLACK AND TAN COONHOUND" : "https://www.fci.be/Nomenclature/Illustrations/300g06.jpg",
	"EAST SIBERIAN LAIKA" : "https://www.fci.be/Nomenclature/Illustrations/305g05-1.jpg",
	"WEST SIBERIAN LAIKA" : "https://www.fci.be/Nomenclature/Illustrations/306g05.jpg",
	"AZAWAKH" : "https://www.fci.be/Nomenclature/Illustrations/307g10-1.jpg",
	"PERUVIAN HAIRLESS DOG" : "https://www.fci.be/Nomenclature/Illustrations/310g05.jpg",
	"SAARLOOS WOLFHOND" : "https://www.fci.be/Nomenclature/Illustrations/311g01-1.jpg",
	"DUTCH SCHAPENDOES" : "https://www.fci.be/Nomenclature/Illustrations/313g01-1.jpg",
	"NEDERLANDSE KOOIKERHONDJE" : "https://www.fci.be/Nomenclature/Illustrations/314g08-1.jpg",
	"BROHOLMER" : "https://www.fci.be/Nomenclature/Illustrations/315g02.jpg",
	"KAI" : "https://www.fci.be/Nomenclature/Illustrations/317g05.jpg",
	"KISHU" : "https://www.fci.be/Nomenclature/Illustrations/318g05.jpg",
	"SHIKOKU" : "https://www.fci.be/Nomenclature/Illustrations/319g05.jpg",
	"GREAT ANGLO-FRENCH WHITE AND BLACK HOUND" : "https://www.fci.be/Nomenclature/Illustrations/323g06.jpg",
	"GREAT ANGLO-FRENCH WHITE & ORANGE HOUND" : "https://www.fci.be/Nomenclature/Illustrations/324g06.jpg",
	"SOUTH RUSSIAN SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/326g01.jpg",
	"RUSSIAN BLACK TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/327g02.jpg",
	"CAUCASIAN SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/328g02.jpg",
	"CANARIAN WARREN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/329g05.jpg",
	"KANGAL SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/331g02.jpg",
	"KOREA JINDO DOG" : "https://www.fci.be/Nomenclature/Illustrations/334g05.jpg",
	"CENTRAL ASIA SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/335g02-1.jpg",
	"ITALIAN SHORT-HAIRED SEGUGIO" : "https://www.fci.be/Nomenclature/Illustrations/337g06.jpg",
	"PARSON RUSSELL TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/339g03.jpg",
	"BRAZILIAN TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/341g03.jpg",
	"ITALIAN CANE CORSO" : "https://www.fci.be/Nomenclature/Illustrations/343g02.jpg",
	"JACK RUSSELL TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/345g03-1.jpg",
	"PRESA CANARIO" : "https://www.fci.be/Nomenclature/Illustrations/346g02.jpg",
	"WHITE SWISS SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/347g01-1.jpg",
	"TAIWAN DOG" : "https://www.fci.be/Nomenclature/Illustrations/348g05.jpg",
	"ROMANIAN MIORITIC SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/349g01.jpg",
	"ROMANIAN CARPATHIAN SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/350g01.jpg",
	"RUSSIAN TOY" : "https://www.fci.be/Nomenclature/Illustrations/352g09-1.jpg",
	"CIMARRÓN URUGUAYO" : "https://www.fci.be/Nomenclature/Illustrations/353g02.jpg",
	"BOSNIAN AND HERZEGOVINIAN - CROATIAN SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/355g02.jpg",
	"DANISH-SWEDISH FARMDOG" : "https://www.fci.be/Nomenclature/Illustrations/356g02.jpg",
	"ROMANIAN BUCOVINA SHEPHERD" : "https://www.fci.be/Nomenclature/Illustrations/357g02.jpg",
	"THAI BANGKAEW DOG" : "https://www.fci.be/Nomenclature/Illustrations/358g05.jpg",
	"MINIATURE BULL TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/359g03.jpg",
	"LANCASHIRE HEELER" : "https://www.fci.be/Nomenclature/Illustrations/360g01.jpg",
	"SEGUGIO MAREMMANO" : "https://www.fci.be/Nomenclature/Illustrations/361g06-1.jpg",
	"KINTAMANI-BALI DOG" : "https://www.fci.be/Nomenclature/Illustrations/362g05.jpg",
	"PRAGUE RATTER" : "https://www.fci.be/Nomenclature/Illustrations/363g09-1.jpg",
	"BOHEMIAN SHEPHERD DOG" : "https://www.fci.be/Nomenclature/Illustrations/364g01-1.jpg",
	"YAKUTIAN LAIKA" : "https://www.fci.be/Nomenclature/Illustrations/365g05-1.jpg",
	"ESTONIAN HOUND" : "https://www.fci.be/Nomenclature/Illustrations/366g06.jpg",
	"TRANSMONTANO MASTIFF" : "https://www.fci.be/Nomenclature/Illustrations/368g02.jpg",
	"CONTINENTAL BULLDOG" : "https://www.fci.be/Nomenclature/Illustrations/369g02.jpg",
	"VALENCIAN TERRIER" : "https://www.fci.be/Nomenclature/Illustrations/370g03.jpg",
}
