image_urls = {
	"english pointer" : "https://www.fci.be/Nomenclature/Illustrations/001g07.jpg",
	"english setter" : "https://www.fci.be/Nomenclature/Illustrations/002g07.jpg",
	"cairn terrier" : "https://www.fci.be/Nomenclature/Illustrations/004g03.jpg",
	"english cocker spaniel" : "https://www.fci.be/Nomenclature/Illustrations/005g08.jpg",
	"gordon setter" : "https://www.fci.be/Nomenclature/Illustrations/006g07.jpg",
	"airedale terrier" : "https://www.fci.be/Nomenclature/Illustrations/007g03.jpg",
	"australian terrier" : "https://www.fci.be/Nomenclature/Illustrations/008g03.jpg",
	"bedlington terrier" : "https://www.fci.be/Nomenclature/Illustrations/009g03.jpg",
	"border terrier" : "https://www.fci.be/Nomenclature/Illustrations/010g03.jpg",
	"bull terrier" : "https://www.fci.be/Nomenclature/Illustrations/011g03.jpg",
	"fox terrier (smooth)" : "https://www.fci.be/Nomenclature/Illustrations/012g03.jpg",
	"english toy terrier (black &tan)" : "https://www.fci.be/Nomenclature/Illustrations/013g03.jpg",
	"swedish vallhund" : "https://www.fci.be/Nomenclature/Illustrations/014g05.jpg",
	"old english sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/016g01.jpg",
	"griffon nivernais" : "https://www.fci.be/Nomenclature/Illustrations/017g06.jpg",
	"briquet griffon vendeen" : "https://www.fci.be/Nomenclature/Illustrations/019g06.jpg",
	"ariegeois" : "https://www.fci.be/Nomenclature/Illustrations/020g06.jpg",
	"gascon saintongeois" : "https://www.fci.be/Nomenclature/Illustrations/021g06-1.jpg",
	"great gascony blue" : "https://www.fci.be/Nomenclature/Illustrations/022g06.jpg",
	"poitevin" : "https://www.fci.be/Nomenclature/Illustrations/024g06.jpg",
	"billy" : "https://www.fci.be/Nomenclature/Illustrations/025g06.jpg",
	"artois hound" : "https://www.fci.be/Nomenclature/Illustrations/028g06.jpg",
	"porcelaine" : "https://www.fci.be/Nomenclature/Illustrations/030g06.jpg",
	"small blue gascony" : "https://www.fci.be/Nomenclature/Illustrations/031g06.jpg",
	"blue gascony griffon" : "https://www.fci.be/Nomenclature/Illustrations/032g06.jpg",
	"norman artesien basset" : "https://www.fci.be/Nomenclature/Illustrations/034g06.jpg",
	"blue gascony basset" : "https://www.fci.be/Nomenclature/Illustrations/035g06.jpg",
	"portuguese water dog" : "https://www.fci.be/Nomenclature/Illustrations/037g08.jpg",
	"welsh corgi (cardigan)" : "https://www.fci.be/Nomenclature/Illustrations/038g01.jpg",
	"welsh corgi (pembroke)" : "https://www.fci.be/Nomenclature/Illustrations/039g01.jpg",
	"jämthund" : "https://www.fci.be/Nomenclature/Illustrations/042g05.jpg",
	"beauce sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/044g01.jpg",
	"bernese mountain dog" : "https://www.fci.be/Nomenclature/Illustrations/045g02.jpg",
	"appenzell cattle dog" : "https://www.fci.be/Nomenclature/Illustrations/046g02.jpg",
	"entlebuch cattle dog" : "https://www.fci.be/Nomenclature/Illustrations/047g02.jpg",
	"karelian bear dog" : "https://www.fci.be/Nomenclature/Illustrations/048g05-1.jpg",
	"finnish spitz" : "https://www.fci.be/Nomenclature/Illustrations/049g05-1.jpg",
	"polish hound" : "https://www.fci.be/Nomenclature/Illustrations/052g06.jpg",
	"komondor" : "https://www.fci.be/Nomenclature/Illustrations/053g01.jpg",
	"kuvasz" : "https://www.fci.be/Nomenclature/Illustrations/054g01.jpg",
	"puli" : "https://www.fci.be/Nomenclature/Illustrations/055g01.jpg",
	"pumi" : "https://www.fci.be/Nomenclature/Illustrations/056g01.jpg",
	"hungarian short-haired pointer (vizsla)" : "https://www.fci.be/Nomenclature/Illustrations/057g07.jpg",
	"great swiss mountain dog" : "https://www.fci.be/Nomenclature/Illustrations/058g02.jpg",
	"swiss hound" : "https://www.fci.be/Nomenclature/Illustrations/059g06-1.jpg",
	"small swiss hound" : "https://www.fci.be/Nomenclature/Illustrations/060g06-1.jpg",
	"st. bernard" : "https://www.fci.be/Nomenclature/Illustrations/061g02-1.jpg",
	"coarse-haired styrian hound" : "https://www.fci.be/Nomenclature/Illustrations/062g06.jpg",
	"austrian black and tan hound" : "https://www.fci.be/Nomenclature/Illustrations/063g06.jpg",
	"fawn brittany griffon" : "https://www.fci.be/Nomenclature/Illustrations/066g06.jpg",
	"lakeland terrier" : "https://www.fci.be/Nomenclature/Illustrations/070g03.jpg",
	"manchester terrier" : "https://www.fci.be/Nomenclature/Illustrations/071g03.jpg",
	"norwich terrier" : "https://www.fci.be/Nomenclature/Illustrations/072g03.jpg",
	"scottish terrier" : "https://www.fci.be/Nomenclature/Illustrations/073g03.jpg",
	"sealyham terrier" : "https://www.fci.be/Nomenclature/Illustrations/074g03.jpg",
	"skye terrier" : "https://www.fci.be/Nomenclature/Illustrations/075g03.jpg",
	"staffordshire bull terrier" : "https://www.fci.be/Nomenclature/Illustrations/076g03.jpg",
	"welsh terrier" : "https://www.fci.be/Nomenclature/Illustrations/078g03.jpg",
	"griffon belge" : "https://www.fci.be/Nomenclature/Illustrations/081g09.jpg",
	"petit brabançon" : "https://www.fci.be/Nomenclature/Illustrations/082g09.jpg",
	"west highland white terrier" : "https://www.fci.be/Nomenclature/Illustrations/085g03.jpg",
	"yorkshire terrier" : "https://www.fci.be/Nomenclature/Illustrations/086g03.jpg",
	"shetland sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/088g01.jpg",
	"portuguese sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/093g01.jpg",
	"portuguese warren hound-portuguese podengo" : "https://www.fci.be/Nomenclature/Illustrations/094g05-1.jpg",
	"brittany spaniel" : "https://www.fci.be/Nomenclature/Illustrations/095g07.jpg",
	"rafeiro of alentejo" : "https://www.fci.be/Nomenclature/Illustrations/096g02.jpg",
	"german spitz" : "https://www.fci.be/Nomenclature/Illustrations/097g05-1.jpg",
	"german wire- haired pointing dog" : "https://www.fci.be/Nomenclature/Illustrations/098g07.jpg",
	"weimaraner" : "https://www.fci.be/Nomenclature/Illustrations/099g07-1.jpg",
	"french bulldog" : "https://www.fci.be/Nomenclature/Illustrations/101g09.jpg",
	"german hunting terrier" : "https://www.fci.be/Nomenclature/Illustrations/103g03-1.jpg",
	"german spaniel" : "https://www.fci.be/Nomenclature/Illustrations/104g08.jpg",
	"french water dog" : "https://www.fci.be/Nomenclature/Illustrations/105g08.jpg",
	"blue picardy spaniel" : "https://www.fci.be/Nomenclature/Illustrations/106g07.jpg",
	"wire-haired pointing griffon korthals" : "https://www.fci.be/Nomenclature/Illustrations/107g07.jpg",
	"picardy spaniel" : "https://www.fci.be/Nomenclature/Illustrations/108g07.jpg",
	"clumber spaniel" : "https://www.fci.be/Nomenclature/Illustrations/109g08.jpg",
	"curly coated retriever" : "https://www.fci.be/Nomenclature/Illustrations/110g08.jpg",
	"golden retriever" : "https://www.fci.be/Nomenclature/Illustrations/111g08.jpg",
	"briard" : "https://www.fci.be/Nomenclature/Illustrations/113g01.jpg",
	"pont-audemer spaniel" : "https://www.fci.be/Nomenclature/Illustrations/114g07.jpg",
	"saint germain pointer" : "https://www.fci.be/Nomenclature/Illustrations/115g07.jpg",
	"dogue de bordeaux" : "https://www.fci.be/Nomenclature/Illustrations/116g02.jpg",
	"deutsch langhaar" : "https://www.fci.be/Nomenclature/Illustrations/117g07.jpg",
	"large munsterlander" : "https://www.fci.be/Nomenclature/Illustrations/118g07.jpg",
	"german short- haired pointing dog" : "https://www.fci.be/Nomenclature/Illustrations/119g07.jpg",
	"flat coated retriever" : "https://www.fci.be/Nomenclature/Illustrations/121g08.jpg",
	"labrador retriever" : "https://www.fci.be/Nomenclature/Illustrations/122g08.jpg",
	"field spaniel" : "https://www.fci.be/Nomenclature/Illustrations/123g08.jpg",
	"english springer spaniel" : "https://www.fci.be/Nomenclature/Illustrations/125g08.jpg",
	"welsh springer spaniel" : "https://www.fci.be/Nomenclature/Illustrations/126g08.jpg",
	"sussex spaniel" : "https://www.fci.be/Nomenclature/Illustrations/127g08.jpg",
	"king charles spaniel" : "https://www.fci.be/Nomenclature/Illustrations/128g09.jpg",
	"smålandsstövare" : "https://www.fci.be/Nomenclature/Illustrations/129g06.jpg",
	"drever" : "https://www.fci.be/Nomenclature/Illustrations/130g06.jpg",
	"schillerstövare" : "https://www.fci.be/Nomenclature/Illustrations/131g06.jpg",
	"hamiltonstövare" : "https://www.fci.be/Nomenclature/Illustrations/132g06.jpg",
	"french pointing dog - gascogne type" : "https://www.fci.be/Nomenclature/Illustrations/133g07.jpg",
	"french pointing dog - pyrenean type" : "https://www.fci.be/Nomenclature/Illustrations/134g07.jpg",
	"swedish lapphund" : "https://www.fci.be/Nomenclature/Illustrations/135g05.jpg",
	"cavalier king charles spaniel" : "https://www.fci.be/Nomenclature/Illustrations/136g09.jpg",
	"pyrenean mountain dog" : "https://www.fci.be/Nomenclature/Illustrations/137g02.jpg",
	"pyrenean sheepdog - smooth faced" : "https://www.fci.be/Nomenclature/Illustrations/138g01.jpg",
	"long-haired pyrenean sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/141g01.jpg",
	"dobermann" : "https://www.fci.be/Nomenclature/Illustrations/143g02.jpg",
	"boxer" : "https://www.fci.be/Nomenclature/Illustrations/144g02.jpg",
	"dachshund" : "https://www.fci.be/Nomenclature/Illustrations/148g04-1.jpg",
	"bulldog" : "https://www.fci.be/Nomenclature/Illustrations/149g02.jpg",
	"serbian hound" : "https://www.fci.be/Nomenclature/Illustrations/150g06.jpg",
	"istrian short-haired hound" : "https://www.fci.be/Nomenclature/Illustrations/151g06.jpg",
	"istrian wire-haired hound" : "https://www.fci.be/Nomenclature/Illustrations/152g06.jpg",
	"dalmatian" : "https://www.fci.be/Nomenclature/Illustrations/153g06.jpg",
	"posavatz hound" : "https://www.fci.be/Nomenclature/Illustrations/154g06.jpg",
	"bosnian broken-haired hound - called barak" : "https://www.fci.be/Nomenclature/Illustrations/155g06.jpg",
	"collie rough" : "https://www.fci.be/Nomenclature/Illustrations/156g01.jpg",
	"greyhound" : "https://www.fci.be/Nomenclature/Illustrations/158g10.jpg",
	"english foxhound" : "https://www.fci.be/Nomenclature/Illustrations/159g06.jpg",
	"beagle" : "https://www.fci.be/Nomenclature/Illustrations/161g06.jpg",
	"whippet" : "https://www.fci.be/Nomenclature/Illustrations/162g10.jpg",
	"basset hound" : "https://www.fci.be/Nomenclature/Illustrations/163g06.jpg",
	"deerhound" : "https://www.fci.be/Nomenclature/Illustrations/164g10.jpg",
	"german shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/166g01-1.jpg",
	"dandie dinmont terrier" : "https://www.fci.be/Nomenclature/Illustrations/168g03.jpg",
	"fox terrier (wire)" : "https://www.fci.be/Nomenclature/Illustrations/169g03.jpg",
	"castro laboreiro dog" : "https://www.fci.be/Nomenclature/Illustrations/170g02.jpg",
	"poodle" : "https://www.fci.be/Nomenclature/Illustrations/172g09.jpg",
	"estrela mountain dog" : "https://www.fci.be/Nomenclature/Illustrations/173g02.jpg",
	"french spaniel" : "https://www.fci.be/Nomenclature/Illustrations/175g07.jpg",
	"picardy sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/176g01.jpg",
	"ariege pointing dog" : "https://www.fci.be/Nomenclature/Illustrations/177g07-1.jpg",
	"bourbonnais pointing dog" : "https://www.fci.be/Nomenclature/Illustrations/179g07.jpg",
	"auvergne pointer" : "https://www.fci.be/Nomenclature/Illustrations/180g07.jpg",
	"giant schnauzer" : "https://www.fci.be/Nomenclature/Illustrations/181g02.jpg",
	"schnauzer" : "https://www.fci.be/Nomenclature/Illustrations/182g02.jpg",
	"miniature schnauzer" : "https://www.fci.be/Nomenclature/Illustrations/183g02.jpg",
	"german pinscher" : "https://www.fci.be/Nomenclature/Illustrations/184g02.jpg",
	"miniature pinscher" : "https://www.fci.be/Nomenclature/Illustrations/185g02.jpg",
	"affenpinscher" : "https://www.fci.be/Nomenclature/Illustrations/186g02.jpg",
	"portuguese pointing dog" : "https://www.fci.be/Nomenclature/Illustrations/187g07.jpg",
	"finnish lapponian dog" : "https://www.fci.be/Nomenclature/Illustrations/189g05-1.jpg",
	"kromfohrländer" : "https://www.fci.be/Nomenclature/Illustrations/192g09.jpg",
	"borzoi - russian hunting sighthound" : "https://www.fci.be/Nomenclature/Illustrations/193g10.jpg",
	"bergamasco shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/194g01-1.jpg",
	"cirneco dell'etna" : "https://www.fci.be/Nomenclature/Illustrations/199g05-1.jpg",
	"italian pointing dog" : "https://www.fci.be/Nomenclature/Illustrations/202g07.jpg",
	"norwegian hound" : "https://www.fci.be/Nomenclature/Illustrations/203g06.jpg",
	"chow chow" : "https://www.fci.be/Nomenclature/Illustrations/205g05.jpg",
	"japanese chin" : "https://www.fci.be/Nomenclature/Illustrations/206g09.jpg",
	"pekingese" : "https://www.fci.be/Nomenclature/Illustrations/207g09.jpg",
	"shih tzu" : "https://www.fci.be/Nomenclature/Illustrations/208g09.jpg",
	"tibetan terrier" : "https://www.fci.be/Nomenclature/Illustrations/209g09.jpg",
	"canadian eskimo dog" : "https://www.fci.be/Nomenclature/Illustrations/211g05.jpg",
	"samoyed" : "https://www.fci.be/Nomenclature/Illustrations/212g05.jpg",
	"hanoverian scent hound" : "https://www.fci.be/Nomenclature/Illustrations/213g06-1.jpg",
	"bichon frise" : "https://www.fci.be/Nomenclature/Illustrations/215g09-1.jpg",
	"bavarian mountain scent hound" : "https://www.fci.be/Nomenclature/Illustrations/217g06-1.jpg",
	"chihuahua" : "https://www.fci.be/Nomenclature/Illustrations/218g09-1.jpg",
	"french tricolour hound" : "https://www.fci.be/Nomenclature/Illustrations/219g06.jpg",
	"french white & black hound" : "https://www.fci.be/Nomenclature/Illustrations/220g06.jpg",
	"wetterhoun" : "https://www.fci.be/Nomenclature/Illustrations/221g08-1.jpg",
	"stabijhoun" : "https://www.fci.be/Nomenclature/Illustrations/222g07-1.jpg",
	"dutch shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/223g01-1.jpg",
	"drentsche partridge dog" : "https://www.fci.be/Nomenclature/Illustrations/224g07-1.jpg",
	"fila brasileiro" : "https://www.fci.be/Nomenclature/Illustrations/225g02.jpg",
	"lhasa apso" : "https://www.fci.be/Nomenclature/Illustrations/227g09.jpg",
	"afghan hound" : "https://www.fci.be/Nomenclature/Illustrations/228g10.jpg",
	"serbian tricolour hound" : "https://www.fci.be/Nomenclature/Illustrations/229g06.jpg",
	"tibetan spaniel" : "https://www.fci.be/Nomenclature/Illustrations/231g09.jpg",
	"deutsch stichelhaar" : "https://www.fci.be/Nomenclature/Illustrations/232g07.jpg",
	"little lion dog" : "https://www.fci.be/Nomenclature/Illustrations/233g09.jpg",
	"xoloitzcuintle" : "https://www.fci.be/Nomenclature/Illustrations/234g05-1.jpg",
	"great dane" : "https://www.fci.be/Nomenclature/Illustrations/235g02.jpg",
	"australian silky terrier" : "https://www.fci.be/Nomenclature/Illustrations/236g03.jpg",
	"norwegian buhund" : "https://www.fci.be/Nomenclature/Illustrations/237g05.jpg",
	"mudi" : "https://www.fci.be/Nomenclature/Illustrations/238g01.jpg",
	"hungarian wire-haired pointer" : "https://www.fci.be/Nomenclature/Illustrations/239g07.jpg",
	"hungarian greyhound" : "https://www.fci.be/Nomenclature/Illustrations/240g10.jpg",
	"hungarian hound - transylvanian scent hound" : "https://www.fci.be/Nomenclature/Illustrations/241g06.jpg",
	"norwegian elkhound grey" : "https://www.fci.be/Nomenclature/Illustrations/242g05.jpg",
	"alaskan malamute" : "https://www.fci.be/Nomenclature/Illustrations/243g05.JPG",
	"cesky terrier" : "https://www.fci.be/Nomenclature/Illustrations/246g03.jpg",
	"polish lowland sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/251g01.jpg",
	"tatra shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/252g01.jpg",
	"pug" : "https://www.fci.be/Nomenclature/Illustrations/253g09.jpg",
	"akita" : "https://www.fci.be/Nomenclature/Illustrations/255g05.jpg",
	"shiba" : "https://www.fci.be/Nomenclature/Illustrations/257g05.jpg",
	"japanese terrier" : "https://www.fci.be/Nomenclature/Illustrations/259g03.jpg",
	"tosa" : "https://www.fci.be/Nomenclature/Illustrations/260g02.jpg",
	"hokkaido" : "https://www.fci.be/Nomenclature/Illustrations/261g05.jpg",
	"japanese spitz" : "https://www.fci.be/Nomenclature/Illustrations/262g05.jpg",
	"norwegian lundehund" : "https://www.fci.be/Nomenclature/Illustrations/265g05.jpg",
	"hygen hound" : "https://www.fci.be/Nomenclature/Illustrations/266g06.jpg",
	"halden hound" : "https://www.fci.be/Nomenclature/Illustrations/267g06.jpg",
	"norwegian elkhound black" : "https://www.fci.be/Nomenclature/Illustrations/268g05.jpg",
	"siberian husky" : "https://www.fci.be/Nomenclature/Illustrations/270g05.jpg",
	"bearded collie" : "https://www.fci.be/Nomenclature/Illustrations/271g01.jpg",
	"norfolk terrier" : "https://www.fci.be/Nomenclature/Illustrations/272g03.jpg",
	"greenland dog" : "https://www.fci.be/Nomenclature/Illustrations/274g05.jpg",
	"brazilian tracker" : "https://www.fci.be/Nomenclature/Illustrations/275g06.jpg",
	"norrbottenspitz" : "https://www.fci.be/Nomenclature/Illustrations/276g05.jpg",
	"croatian shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/277g01.jpg",
	"karst shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/278g02.jpg",
	"montenegrin mountain hound" : "https://www.fci.be/Nomenclature/Illustrations/279g06.jpg",
	"grand griffon vendeen" : "https://www.fci.be/Nomenclature/Illustrations/282g06.jpg",
	"australian cattle dog" : "https://www.fci.be/Nomenclature/Illustrations/287g01.jpg",
	"chinese crested dog" : "https://www.fci.be/Nomenclature/Illustrations/288g09.jpg",
	"icelandic sheepdog" : "https://www.fci.be/Nomenclature/Illustrations/289g05.jpg",
	"beagle harrier" : "https://www.fci.be/Nomenclature/Illustrations/290g06.jpg",
	"eurasian" : "https://www.fci.be/Nomenclature/Illustrations/291g05-1.jpg",
	"dogo argentino" : "https://www.fci.be/Nomenclature/Illustrations/292g02.jpg",
	"australian kelpie" : "https://www.fci.be/Nomenclature/Illustrations/293g01.jpg",
	"otterhound" : "https://www.fci.be/Nomenclature/Illustrations/294g06.jpg",
	"collie smooth" : "https://www.fci.be/Nomenclature/Illustrations/296g01.jpg",
	"border collie" : "https://www.fci.be/Nomenclature/Illustrations/297g01.jpg",
	"romagna water dog" : "https://www.fci.be/Nomenclature/Illustrations/298g08-1.jpg",
	"black and tan coonhound" : "https://www.fci.be/Nomenclature/Illustrations/300g06.jpg",
	"east siberian laika" : "https://www.fci.be/Nomenclature/Illustrations/305g05-1.jpg",
	"west siberian laika" : "https://www.fci.be/Nomenclature/Illustrations/306g05.jpg",
	"azawakh" : "https://www.fci.be/Nomenclature/Illustrations/307g10-1.jpg",
	"peruvian hairless dog" : "https://www.fci.be/Nomenclature/Illustrations/310g05.jpg",
	"saarloos wolfhond" : "https://www.fci.be/Nomenclature/Illustrations/311g01-1.jpg",
	"dutch schapendoes" : "https://www.fci.be/Nomenclature/Illustrations/313g01-1.jpg",
	"nederlandse kooikerhondje" : "https://www.fci.be/Nomenclature/Illustrations/314g08-1.jpg",
	"broholmer" : "https://www.fci.be/Nomenclature/Illustrations/315g02.jpg",
	"kai" : "https://www.fci.be/Nomenclature/Illustrations/317g05.jpg",
	"kishu" : "https://www.fci.be/Nomenclature/Illustrations/318g05.jpg",
	"shikoku" : "https://www.fci.be/Nomenclature/Illustrations/319g05.jpg",
	"great anglo-french white and black hound" : "https://www.fci.be/Nomenclature/Illustrations/323g06.jpg",
	"great anglo-french white & orange hound" : "https://www.fci.be/Nomenclature/Illustrations/324g06.jpg",
	"south russian shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/326g01.jpg",
	"russian black terrier" : "https://www.fci.be/Nomenclature/Illustrations/327g02.jpg",
	"caucasian shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/328g02.jpg",
	"canarian warren hound" : "https://www.fci.be/Nomenclature/Illustrations/329g05.jpg",
	"kangal shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/331g02.jpg",
	"korea jindo dog" : "https://www.fci.be/Nomenclature/Illustrations/334g05.jpg",
	"central asia shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/335g02-1.jpg",
	"italian short-haired segugio" : "https://www.fci.be/Nomenclature/Illustrations/337g06.jpg",
	"parson russell terrier" : "https://www.fci.be/Nomenclature/Illustrations/339g03.jpg",
	"brazilian terrier" : "https://www.fci.be/Nomenclature/Illustrations/341g03.jpg",
	"italian cane corso" : "https://www.fci.be/Nomenclature/Illustrations/343g02.jpg",
	"jack russell terrier" : "https://www.fci.be/Nomenclature/Illustrations/345g03-1.jpg",
	"presa canario" : "https://www.fci.be/Nomenclature/Illustrations/346g02.jpg",
	"white swiss shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/347g01-1.jpg",
	"taiwan dog" : "https://www.fci.be/Nomenclature/Illustrations/348g05.jpg",
	"romanian mioritic shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/349g01.jpg",
	"romanian carpathian shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/350g01.jpg",
	"russian toy" : "https://www.fci.be/Nomenclature/Illustrations/352g09-1.jpg",
	"cimarrón uruguayo" : "https://www.fci.be/Nomenclature/Illustrations/353g02.jpg",
	"bosnian and herzegovinian - croatian shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/355g02.jpg",
	"danish-swedish farmdog" : "https://www.fci.be/Nomenclature/Illustrations/356g02.jpg",
	"romanian bucovina shepherd" : "https://www.fci.be/Nomenclature/Illustrations/357g02.jpg",
	"thai bangkaew dog" : "https://www.fci.be/Nomenclature/Illustrations/358g05.jpg",
	"miniature bull terrier" : "https://www.fci.be/Nomenclature/Illustrations/359g03.jpg",
	"lancashire heeler" : "https://www.fci.be/Nomenclature/Illustrations/360g01.jpg",
	"segugio maremmano" : "https://www.fci.be/Nomenclature/Illustrations/361g06-1.jpg",
	"kintamani-bali dog" : "https://www.fci.be/Nomenclature/Illustrations/362g05.jpg",
	"prague ratter" : "https://www.fci.be/Nomenclature/Illustrations/363g09-1.jpg",
	"bohemian shepherd dog" : "https://www.fci.be/Nomenclature/Illustrations/364g01-1.jpg",
	"yakutian laika" : "https://www.fci.be/Nomenclature/Illustrations/365g05-1.jpg",
	"estonian hound" : "https://www.fci.be/Nomenclature/Illustrations/366g06.jpg",
	"transmontano mastiff" : "https://www.fci.be/Nomenclature/Illustrations/368g02.jpg",
	"continental bulldog" : "https://www.fci.be/Nomenclature/Illustrations/369g02.jpg",
	"valencian terrier" : "https://www.fci.be/Nomenclature/Illustrations/370g03.jpg",
}